/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack1;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author MaikaB
 */
public class BuildTeam extends javax.swing.JFrame {

    /**
     * Creates new form BuildTeam
     * @throws java.lang.ClassNotFoundException
     */
    public BuildTeam() throws ClassNotFoundException {
        initComponents();
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null; 
        CallableStatement pstmt = null;
        
         try {
            // Establish the connection to the database.
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/pokemon?" + 
                    "user=cpsc408&password=FY17cpsc408&noAccessToProcedureBodies=true");
            
            //Pokedex display table.
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT name FROM Attributes");
            java.sql.ResultSetMetaData rsmetadata = rs.getMetaData();
            
            //pass data into jtable
            DefaultListModel dlm = new DefaultListModel();
     
            while(rs.next()){
                String name = rs.getString("name");
                dlm.addElement(name);
            }
            //pass default table data into pokeList
            pokeList.setModel(dlm);
            //END OF Attributes DISPLAY BLOCK.
                 
         }catch (SQLException ex) {
            // Handle any SQL errors.
            System.out.println("SQLException: "+ ex.getMessage());
            System.out.println("SQLState: "+ ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } finally {
            // Close the result set handle.
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) { /* Ignore. */ }
                rs = null;
            }
            // Close the statement handle.
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException ex) { /* Ignore. */ }
                stmt = null;
            }
            // Close the connection handle.
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) { /* Ignore. */ }
                conn = null;
            }
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pokeList = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        teamList = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Team Builder");

        jScrollPane1.setViewportView(pokeList);

        jButton1.setText("Add to Team >>");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(teamList);

        jLabel2.setText("Pokemon");

        jButton2.setText("<< Remove");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Rules:\n1. Team Size limited to 6.\n2. tbd");
        jScrollPane3.setViewportView(jTextArea1);

        jButton3.setText("Continue");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTextName.setText("Enter Team Name");
        jTextName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton1))
                                        .addGap(21, 21, 21))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jTextName))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jButton4)
                .addGap(102, 102, 102)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton4))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //add pokemon to your team.
    DefaultListModel dim = new DefaultListModel();
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(teamList.getModel().getSize() <= 5){
            dim.addElement(pokeList.getSelectedValue());
            teamList.setModel(dim);
        }
        else{
            System.out.println("No action Performed, team size needs to meet reqs.");
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed
    //remove pokemon from your team
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dim.removeElement(teamList.getSelectedValue());
        teamList.setModel(dim);
    }//GEN-LAST:event_jButton2ActionPerformed
    //Go back to Main Menu
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame backButton = new MainMenu();
        backButton.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        backButton.setLocationRelativeTo(null);
        backButton.setVisible(true);  
    }//GEN-LAST:event_jButton4ActionPerformed
    //Stored Procedure checks if team name already exists in database.
    private void jTextNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNameActionPerformed
        // TODO add your handling code here:
        //String teamName = jTextName.getText();
        Connection conn = null;
        ResultSet rs = null; 
        Statement stmt = null;
        CallableStatement pstmt = null;
        try {
            // Establish the connection to the database.
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/pokemon?" + 
                    "user=cpsc408&password=FY17cpsc408&noAccessToProcedureBodies=true");
            //Database check Name
            
            pstmt = conn.prepareCall("{ call team_name(?) }");
            String name = jTextName.getText();
            pstmt.setString(1,name);
            pstmt.execute();
         }catch (SQLException ex) {
            // Handle any SQL errors.
            System.out.println("SQLException: "+ ex.getMessage());
            System.out.println("SQLState: "+ ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            // Close the result set handle.
            if (rs != null) {
                try {
                    rs.close();} catch (SQLException ex) { /* Ignore. */ }
                rs = null;}
            // Close the statement handle.
            if (stmt != null) {
                try {
                    stmt.close();} catch (SQLException ex) { /* Ignore. */ }
                    stmt = null;}
            // Close the connection handle.
            if (conn != null) {try {conn.close();} catch (SQLException ex) { /* Ignore. */ }
                conn = null;}
         }
    }//GEN-LAST:event_jTextNameActionPerformed
    //Continue button will update the team table with new team info.
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {                                         
            // TODO add your handling code here:
            //get teamName
            String name = jTextName.getText();
            System.out.println(name);
            //get team members
            String poke1 = "";
            String poke2="";
            String poke3="";
            String poke4="";
            String poke5="";
            String poke6="";
            if(teamList.getModel().getSize() >= 5){
                for(int i = 0; i< teamList.getModel().getSize();i++){
                    poke1 = teamList.getModel().getElementAt(0);
                    poke2 = teamList.getModel().getElementAt(1);
                    poke3 = teamList.getModel().getElementAt(2);
                    poke4 = teamList.getModel().getElementAt(3);
                    poke5 = teamList.getModel().getElementAt(4);
                    poke6 = teamList.getModel().getElementAt(5);
                }
            }
            else{
                System.out.println("Did not meet team length standards.");
            }
            Connection conn = null;
            ResultSet rs = null;
            Statement stmt = null;
            CallableStatement pstmt = null;
            try {
                // Establish the connection to the database.
                Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
                conn = DriverManager.getConnection("jdbc:mysql://localhost/pokemon?" +
                        "user=cpsc408&password=FY17cpsc408&noAccessToProcedureBodies=true");
                //Database check Name
                
                pstmt = conn.prepareCall("{ call insert_team(?,?,?,?,?,?,?) }");
                pstmt.setString(1,name);
                pstmt.setString(2,poke1);
                pstmt.setString(3,poke2);
                pstmt.setString(4,poke3);
                pstmt.setString(5,poke4);
                pstmt.setString(6,poke5);
                pstmt.setString(7,poke6);
                pstmt.execute();
                
                
            }catch (SQLException ex) {
                // Handle any SQL errors.
                System.out.println("SQLException: "+ ex.getMessage());
                System.out.println("SQLState: "+ ex.getSQLState());
                System.out.println("VendorError: " + ex.getErrorCode());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
            } finally {
                // Close the result set handle.
                if (rs != null) {
                    try {
                        rs.close();} catch (SQLException ex) { /* Ignore. */ }
                    rs = null;}
                // Close the statement handle.
                if (stmt != null) {
                    try {
                        stmt.close();} catch (SQLException ex) { /* Ignore. */ }
                    stmt = null;}
                // Close the connection handle.
                if (conn != null) {try {conn.close();} catch (SQLException ex) { /* Ignore. */ }
                conn = null;}
            }
            //Take you to next screen.
            dispose();
            JFrame displayTeamInfo = new displayTeamInfo();
            displayTeamInfo.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            displayTeamInfo.setLocationRelativeTo(null);
            displayTeamInfo.setVisible(true);      
        }catch (ClassNotFoundException ex) {
            Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuildTeam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new BuildTeam().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(BuildTeam.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextName;
    private javax.swing.JList<String> pokeList;
    private javax.swing.JList<String> teamList;
    // End of variables declaration//GEN-END:variables
}
