/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pack1;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MaikaB
 */
public class DisplayStats extends javax.swing.JFrame {

    /**
     * Creates new form DisplayStats
     */
    public DisplayStats() throws ClassNotFoundException {
        initComponents();
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        Scanner reader = new Scanner(System.in); 
        CallableStatement pstmt = null;
         try {
            // Establish the connection to the database.
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/pokemon?" + 
                    "user=cpsc408&password=FY17cpsc408&noAccessToProcedureBodies=true");
            
            //Pokedex display table.
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM Attributes");
            ResultSetMetaData rsmetadata = rs.getMetaData();
            //store number of columns
            int columns = rsmetadata.getColumnCount();
            //pass data into jtable
            DefaultTableModel dtm = new DefaultTableModel();
            Vector column_names = new Vector();
            Vector data_rows = new Vector();
            for(int i = 1; i <= columns; ++i){
                column_names.addElement(rsmetadata.getColumnName(i));
            }
            dtm.setColumnIdentifiers(column_names);
            while(rs.next()){
                data_rows = new Vector();
                for(int j =1; j <= columns; ++j){
                    data_rows.addElement(rs.getString(j));
                }
                dtm.addRow(data_rows);   
            }
            //pass default table data into dexTable
            AttrTable.setModel(dtm);
            //END OF Attributes DISPLAY BLOCK.
            
            
            
            
            
            
            
            
         }catch (SQLException ex) {
            // Handle any SQL errors.
            System.out.println("SQLException: "+ ex.getMessage());
            System.out.println("SQLState: "+ ex.getSQLState());
            System.out.println("VendorError: " + ex.getErrorCode());
        } finally {
            // Close the result set handle.
            if (rs != null) {
                try {
                    rs.close();
                } catch (SQLException ex) { /* Ignore. */ }
                rs = null;
            }
            // Close the statement handle.
            if (stmt != null) {
                try {
                    stmt.close();
                } catch (SQLException ex) { /* Ignore. */ }
                stmt = null;
            }
            // Close the connection handle.
            if (conn != null) {
                try {
                    conn.close();
                } catch (SQLException ex) { /* Ignore. */ }
                conn = null;
            }
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AttrTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AttrTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(AttrTable);

        jLabel1.setText("Pokemon Attributes");

        jButton1.setText("Pokemon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(42, 42, 42)
                                .addComponent(jLabel1))
                            .addComponent(jButton1))
                        .addGap(0, 146, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Dispaly Pokedex button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame displayAttrs = null;
        try {
            displayAttrs = new DisplayPokedex();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DisplayStats.class.getName()).log(Level.SEVERE, null, ex);
        }
        displayAttrs.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        displayAttrs.setLocationRelativeTo(null);
        displayAttrs.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    //Main Menu Button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
        JFrame backButton = new MainMenu();
        backButton.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        backButton.setLocationRelativeTo(null);
        backButton.setVisible(true); 
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayStats.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DisplayStats().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(DisplayStats.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AttrTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
